PDF auf dem Server speichern
FriendsOfREDAXO/pdfout pull request #50
Opened 2022-04-28 15:24 UTC by danspringer

Mit dem Parameter "$saveToPath" kann man einen Pfad definieren, auf welchem die generierte PDF auf dem Server gespeichert wird.

https://github.com/FriendsOfREDAXO/pdfout/issues/49

2022-04-30 15:48 UTC, skerbis requested changes
Bitte meinen Kommentar beachten

2022-04-30 15:48 UTC, skerbis commented on lib/pdfout.php
> +            file_put_contents($saveToPath.rex_string::normalize($name).'.pdf', $pdf->output());
Cool
Bitte rex_file::put verwenden https://www.redaxo.org/doku/main/file#rexfile_put

2022-04-30 16:04 UTC, danspringer commented on lib/pdfout.php
> +            file_put_contents($saveToPath.rex_string::normalize($name).'.pdf', $pdf->output());
Habe ich angepasst: https://github.com/FriendsOfREDAXO/pdfout/pull/50/commits/015a476b51d7cdc2afd4a1cf9ef9b7ea673fbba8

2022-04-30 16:27 UTC, skerbis commented on lib/pdfout.php
> +            file_put_contents($saveToPath.rex_string::normalize($name).'.pdf', $pdf->output());
😘

2022-04-30 16:28 UTC, merged

2022-05-01 12:29 UTC, crydotsnake commented
Sehr cool! :)